# Generated by Django 3.2.18 on 2023-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='reviews',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='thumb_down',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='thumb_up',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
