# Generated by Django 3.2.18 on 2023-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0003_auto_20230503_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='RecipePost',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
