# Generated by Django 3.2.18 on 2023-05-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0005_recipepost_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='post',
            new_name='blog',
        ),
    ]
