# Generated by Django 3.2.18 on 2023-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0006_rename_post_usercomment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='thumb_down',
        ),
        migrations.RemoveField(
            model_name='recipepost',
            name='thumb_up',
        ),
    ]
