# Generated by Django 3.2.19 on 2023-05-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0007_auto_20230513_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='rate',
        ),
    ]
