# Generated by Django 3.2.19 on 2023-05-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0009_remove_recipepost_readtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='victoriabakeryblog.recipepost'),
        ),
    ]
