# Generated by Django 3.2.19 on 2023-05-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0010_auto_20230515_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepost',
            old_name='excerpt',
            new_name='ingredients',
        ),
    ]
